#!/usr/bin/env python3
"""
Quiter PWA build helper. Run from the repo root before every deploy:

    python tools/pwa_build.py            # apply
    python tools/pwa_build.py --check    # only verify (exit code 1 if something is off) — good for CI

It is idempotent and has no dependencies. It does three things:

 1. Writes the PWA <head> block (manifest link, iOS meta tags, apple-touch-icons,
    splash screens) into every frontend/*.html, between <!-- PWA:start --> and <!-- PWA:end -->.
 2. Regenerates the PRECACHE list and the cache VERSION inside frontend/sw.js from the files
    on disk. The version is a hash of those files, so every deploy that changes the shell
    gets a fresh cache and old ones are deleted automatically — nothing to bump by hand.
 3. Checks everything the app needs actually exists (icons, splash images, manifest targets).
"""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "frontend"
CHECK_ONLY = "--check" in sys.argv

# Pages that are part of the offline app shell. Pages that carry secrets in the URL are NOT cached.
SHELL_PAGES = ["index.html", "plans.html", "dashboard.html", "progress.html", "custom-plan.html",
               "custom-plan-athletics.html", "profile.html", "offline.html"]
EXTRA_FILES = ["favicon.svg", "manifest.webmanifest"]
PRECACHE_DIRS = [("assets/css", {".css"}), ("assets/js", {".js"}), ("assets/pwa/icons", {".png"}), ("assets/media", {".jpg", ".jpeg", ".png", ".webp"})]

START, END = "<!-- PWA:start (generated by tools/pwa_build.py - edit the tool, not this block) -->", "<!-- PWA:end -->"
errors = []


def splash_links():
    sizes = json.loads((ROOT / "assets/pwa/splash.json").read_text()) if (ROOT / "assets/pwa/splash.json").exists() else []
    out = []
    for w, h, cw, ch, dpr in sizes:
        f = f"assets/pwa/splash/splash-{w}x{h}.png"
        if not (ROOT / f).exists():
            errors.append(f"missing splash image {f}")
        out.append(f'<link rel="apple-touch-startup-image" media="(device-width: {cw}px) and (device-height: {ch}px) and '
                   f'(-webkit-device-pixel-ratio: {dpr}) and (orientation: portrait)" href="{f}">')
    return out


def head_block(has_theme_color):
    lines = [START,
             '<link rel="manifest" href="manifest.webmanifest">',
             '<meta name="application-name" content="Quiter">',
             '<meta name="mobile-web-app-capable" content="yes">',
             '<meta name="apple-mobile-web-app-capable" content="yes">',
             '<meta name="apple-mobile-web-app-title" content="Quiter">',
             '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">',
             '<meta name="format-detection" content="telephone=no">']
    if not has_theme_color:
        lines.append('<meta name="theme-color" content="#000000">')
    lines += ['<link rel="icon" type="image/png" sizes="32x32" href="assets/pwa/icons/favicon-32.png">',
              '<link rel="apple-touch-icon" href="assets/pwa/icons/apple-touch-icon-180.png">',
              '<link rel="apple-touch-icon" sizes="152x152" href="assets/pwa/icons/apple-touch-icon-152.png">',
              '<link rel="apple-touch-icon" sizes="167x167" href="assets/pwa/icons/apple-touch-icon-167.png">',
              '<link rel="apple-touch-icon" sizes="180x180" href="assets/pwa/icons/apple-touch-icon-180.png">']
    lines += splash_links()
    lines.append(END)
    return lines


def update_html(path):
    raw = path.read_bytes().decode("utf-8")
    crlf = "\r\n" in raw
    text = raw.replace("\r\n", "\n")
    block_re = re.compile(re.escape("<!-- PWA:start") + r".*?" + re.escape(END) + r"\n?", re.S)
    without = block_re.sub("", text)
    if "</head>" not in without:
        errors.append(f"{path.name}: no </head>")
        return
    has_theme = bool(re.search(r'<meta\s+name="theme-color"', without))
    block = "\n".join(head_block(has_theme)) + "\n"
    new = without.replace("</head>", block + "</head>", 1)
    if new != text:
        if CHECK_ONLY:
            errors.append(f"{path.name}: PWA head block out of date (run tools/pwa_build.py)")
        else:
            path.write_bytes((new.replace("\n", "\r\n") if crlf else new).encode("utf-8"))


def precache_files():
    files = [f for f in SHELL_PAGES + EXTRA_FILES]
    for d, exts in PRECACHE_DIRS:
        base = ROOT / d
        if base.exists():
            files += sorted(str(p.relative_to(ROOT)).replace("\\", "/") for p in base.rglob("*") if p.is_file() and p.suffix.lower() in exts)
    missing = [f for f in files if not (ROOT / f).exists()]
    errors.extend(f"precache file missing: {f}" for f in missing)
    return ["./"] + sorted(set(f for f in files if f not in missing))


def update_sw(files):
    sw = ROOT / "sw.js"
    raw = sw.read_bytes().decode("utf-8")
    crlf = "\r\n" in raw
    text = raw.replace("\r\n", "\n")
    h = hashlib.sha1()
    for f in files:
        if f == "./":
            f = "index.html"
        h.update(f.encode()); h.update((ROOT / f).read_bytes())
    version = h.hexdigest()[:10]
    listing = "const PRECACHE = [\n" + "".join(f"  '{f}',\n" for f in files) + "];"
    new = re.sub(r"/\* VERSION:start \*/.*?/\* VERSION:end \*/", f"/* VERSION:start */\nconst VERSION = '{version}';\n/* VERSION:end */", text, flags=re.S)
    new = re.sub(r"/\* PRECACHE:start \*/.*?/\* PRECACHE:end \*/", f"/* PRECACHE:start */\n{listing}\n/* PRECACHE:end */", new, flags=re.S)
    if new != text:
        if CHECK_ONLY:
            errors.append("sw.js precache list / version out of date (run tools/pwa_build.py)")
        else:
            sw.write_bytes((new.replace("\n", "\r\n") if crlf else new).encode("utf-8"))
    return version


def check_manifest():
    m = json.loads((ROOT / "manifest.webmanifest").read_text(encoding="utf-8"))
    for key in ("name", "short_name", "start_url", "display", "icons", "background_color", "theme_color"):
        if key not in m:
            errors.append(f"manifest: missing '{key}'")
    for icon in m.get("icons", []):
        if not (ROOT / icon["src"]).exists():
            errors.append(f"manifest: icon not found {icon['src']}")
    start = m["start_url"].split("?")[0].lstrip("./")
    if start and not (ROOT / start).exists():
        errors.append(f"manifest: start_url target missing {start}")


def main():
    for html in sorted(ROOT.glob("*.html")):
        update_html(html)
    files = precache_files()
    version = update_sw(files) if not errors else "?"
    check_manifest()
    if errors:
        print("PWA build problems:\n  - " + "\n  - ".join(errors))
        sys.exit(1)
    print(f"PWA ok: {len(list(ROOT.glob('*.html')))} pages, {len(files)} precached files, cache version {version}"
          + (" (check only)" if CHECK_ONLY else ""))


if __name__ == "__main__":
    main()
